### PR TITLE
Run CI on pull request

### PR DESCRIPTION
**Pull request by jpascual1994**
Configure CI to run when a pull request is opened

### CODE REVIEW

**Review by santib — APPROVED** [review]
👏

**Review by fedeagripa — APPROVED** [review]

**Review by vitogit — APPROVED** [review]

**Comment by juanmanuelramallo** [comment]
Awesomeeeee! Thank you!

Although I think we are missing something because the CI was run twice for both push and pull_request events
image

**Comment by jpascual1994** [comment]
> Awesomeeeee! Thank you!
> 
> Although I think we are missing something because the CI was run twice for both push and pull_request events
> image

Yes, it runs when someone pushes the branch and again when the PR is opened. We can change it to only run on pull requests.
BTW, I've checked and Rails have the same config https://github.com/rails/rails/blob/master/.github/workflows/rubocop.yml

**Comment by juanmanuelramallo** [comment]
No I guess it's fine as it is, because we would also want to have the CI run against master (which won't be a Pull Request)

**Comment by juanmanuelramallo** [comment]
Let's Get This Merged 
LGTM

**Pull request merged**
